#ifndef VEHICLECONFIG_HPP
#define VEHICLECONFIG_HPP

// MOTOR PINS
#define FRONT_EN_A_PIN 3
#define FRONT_IN_1_PIN 2
#define FRONT_IN_2_PIN 4
#define FRONT_IN_3_PIN 5
#define FRONT_IN_4_PIN 7
#define FRONT_EN_B_PIN 9
#define BACK_EN_A_PIN 10
#define BACK_IN_1_PIN 15
#define BACK_IN_2_PIN 16
#define BACK_IN_3_PIN 17
#define BACK_IN_4_PIN 18
#define BACK_EN_B_PIN 11

//OTHER PINS
#define STATUS_LED_PIN 12

#endif /* VEHICLECONFIG_HPP */
